version: '3'
services:
  web:
    build: .
    ports:
    - 8000:8000
    environment:
    - DB_DBNAME:testing
    - DB_PORT:5432
    - DB_USER:postgres
    - DB_PASS:postgres
    - DB_HOST:127.0.0.1
    network_mode: host
